#!/bin/bash
set -e

# add a huginn group and user
adduser --group huginn
adduser --disabled-login --ingroup huginn --gecos 'Huginn' --no-create-home --home /app huginn
passwd -d huginn

# Shallow clone the huginn project repo
# FIXME
#git clone --depth 1 https://github.com/cantino/huginn /app
git clone --depth 1 -b sqlite https://github.com/dsander/huginn /app

# Change the ownership to huginn
chown -R huginn:huginn /app

cd app

# create required tmp and log directories
sudo -u huginn -H mkdir -p tmp/pids tmp/cache tmp/sockets log
chmod -R u+rwX log tmp

# HACK: We need a database connection to precompile the assets, use sqlite for that
sudo -u huginn -H RAILS_ENV=production DATABASE_ADAPTER=sqlite3 APP_SECRET_TOKEN=secret ON_HEROKU=true bundle install --without test development --path vendor/bundle -j 4
sudo -u huginn -H RAILS_ENV=production DATABASE_ADAPTER=sqlite3 APP_SECRET_TOKEN=secret ON_HEROKU=true bundle exec rake assets:clean assets:precompile

# Bundle again to get rid of the sqlite4 gem
sudo -u huginn -H ON_HEROKU=true DATABASE_ADAPTER=noop bundle install --without test development --path vendor/bundle

# Configure the unicorn server
mv config/unicorn.rb.example config/unicorn.rb
sed -ri 's/^listen .*$/listen ENV["PORT"]/' config/unicorn.rb
sed -ri 's/^stderr_path.*$//' config/unicorn.rb
sed -ri 's/^stdout_path.*$//' config/unicorn.rb

# silence setlocale message (THANKS DEBIAN!)
cat > /etc/default/locale <<EOF
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
EOF

